name: CI/CD - DEV (Validación básica)

on:
  push:
    branches:
      - dev
    paths:
      - 'infra/dev/**'
      - 'dags/**'

jobs:
  validate-dags:
    name: Validar DAGs DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar DAGs Airflow
        run: |
          unzip dags/GCP_ETL_CI_CD_AS400.zip -d dags/
          pip install apache-airflow
          python -m py_compile dags/dag_as400_etl.py || echo "::error:: DAG inválido"

  terraform-validate:
    name: Validar Terraform DEV
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/dev
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate