name: CI/CD - PRD (Terraform Deploy Manual)

on:
  push:
    branches:
      - main
    paths:
      - 'infra/prd/**'
      - 'dags/**'

jobs:
  validate-dags:
    name: Validar DAGs PRD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar DAGs Airflow
        run: |
          unzip dags/GCP_ETL_CI_CD_AS400.zip -d dags/
          pip install apache-airflow
          python -m py_compile dags/dag_as400_etl.py || echo "::error:: DAG inválido"

  terraform-plan:
    name: Terraform Plan PRD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/prd
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

  manual-approval:
    name: Esperar Aprobación Manual
    runs-on: ubuntu-latest
    needs: [validate-dags, terraform-plan]
    steps:
      - name: Esperando aprobación...
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  terraform-apply:
    name: Terraform Apply PRD
    runs-on: ubuntu-latest
    needs: manual-approval
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: infra/prd
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve